# Generated by Django 3.0.6 on 2020-07-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Principal', 'Principal'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=25),
        ),
    ]
